name: Nightly Workflow

on: workflow_dispatch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposit
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install any required dependencies

      - name: Run Python script
        run: python rho_scrape.py  # Replace with the actual filename of your Python script
        
      - name: commit files
        run: |
          git config --local user.email "geversde@andrew.cmu.edu"
          git config --local user.name "Graham Eversden"
          git add -A

      - name: Print current working directory
        run: echo $PWD

      - name: Check file existence
          run: ls  

      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: /home/runner/work/python-github-action-template/python-github-action-template/mlb.csv


      - name: Move CSV file
        run: mv mlb.csv rho_output

        
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          #repository: geversde/python-github-action-template
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

