name: Nightly Workflow

on: workflow_dispatch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install any required dependencies

      - name: Run Python script
        run: python rho_scrape.py  # Replace with the actual filename of your Python script

      - name: Move CSV file
        run: mv mlb*.csv rho_output
        working-directory: https://github.com/geversde/python-github-action-template/

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACCESS_KEY }}
          branch: main

