name: Nightly Workflow

on: workflow_dispatch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install any required dependencies

      - name: Run Python script
        run: python rho_scrape.py  # Replace with the actual filename of your Python script

      - name: Move CSV file
        run: mv mlb*.csv rho_output
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        run: |
          git config --global user.name "Graham Eversden"
          git config --global user.email "geversde@andrew.cmu.edu"
          git add .
          git commit -m "Add CSV file"
          git push
